
const main = async () => {

};

main().catch(exc => {
    console.error(exc);
    alert('Main function execution failed - ' + exc);
});